import React, { useMemo, useState } from "react";
import { sourceNodes, connections } from "./adapters/index.mjs";
import { commentsKey, checkComments, addComment, resolveComment } from "./comments.mjs";

export default function CommentsPanel({ document, identity }) {
  const key = commentsKey(identity || "import"), [version, setVersion] = useState(0), [subject, setSubject] = useState("document:"), [text, setText] = useState(""), [error, setError] = useState("");
  const record = useMemo(() => { try { return checkComments(JSON.parse(localStorage.getItem(key) || '{"version":1,"comments":[]}'), document); } catch (cause) { setTimeout(() => setError(cause.message)); return { version: 1, comments: [] }; } }, [key, document, version]);
  const write = (next) => { localStorage.setItem(key, JSON.stringify(next)); setVersion((value) => value + 1); setError(""); };
  const options = [{ value: "document:", label: "Whole document" }, ...sourceNodes(document).map((item) => ({ value: `item:${item.id}`, label: `Item · ${item.label || item.id}` })), ...connections(document).filter((edge) => edge.id).map((edge) => ({ value: `connection:${edge.id}`, label: `Connection · ${edge.label || edge.id}` }))];
  return <div className="properties"><h2>Comments and review</h2><p>Local review threads use stable subject IDs and stay outside diagram JSON. Deleted subjects remain visible as orphaned threads.</p>{error && <p role="alert">{error}</p>}<form onSubmit={(event) => { event.preventDefault(); const [kind, id] = subject.split(":"); try { write(addComment(record, document, { kind, ...(id ? { id } : {}) }, text)); setText(""); } catch (cause) { setError(cause.message); } }}><label className="field">Subject<select value={subject} onChange={(event) => setSubject(event.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label className="field">Comment<textarea value={text} maxLength={2000} required onChange={(event) => setText(event.target.value)} /></label><button>Add comment</button></form>{record.comments.map((comment) => <section className="checkpoint" key={comment.id}><h3>{comment.subject.kind}{comment.subject.id ? ` · ${comment.subject.id}` : ""}</h3><p>{comment.text}</p><p>{comment.author} · {new Date(comment.createdAt).toLocaleString()}{comment.orphaned ? " · Subject deleted" : ""}</p><button onClick={() => write(resolveComment(record, document, comment.id, !comment.resolvedAt))}>{comment.resolvedAt ? "Reopen" : "Resolve"}</button></section>)}{!record.comments.length && <p>No review comments yet.</p>}</div>;
}
