import React, { useState } from "react";
import { packsKey, builtInPacks, checkPack, installPack } from "./diagram-packs.mjs";
import { templateKey, checkTemplates } from "./templates.mjs";

export default function DiagramPacksPanel({ onStart, onDownload, onValidate }) {
  const read = () => { try { const stored = JSON.parse(localStorage.getItem(packsKey) || "[]"); return builtInPacks.reduce((all, entry) => installPack(all, entry, true), Array.isArray(stored) ? stored.map(checkPack) : []); } catch { return builtInPacks; } };
  const [packs, setPacks] = useState(read), [error, setError] = useState("");
  const write = (next) => { localStorage.setItem(packsKey, JSON.stringify(next.filter((entry) => !builtInPacks.some((builtin) => builtin.id === entry.id)))); setPacks(next); };
  return <div className="properties"><h2>Diagram packs</h2><p>Local packs bundle validated starters, reusable structures, terminology, and an editor accent. Diagram JSON remains unchanged until you explicitly start or insert content.</p>{error && <p role="alert">{error}</p>}<label className="field">Import pack<input type="file" accept=".json,application/json" onChange={async (event) => { const file = event.target.files[0]; event.target.value = ""; if (!file) return; try { const incoming = checkPack(JSON.parse(await file.text())); let next; try { next = installPack(packs, incoming); } catch (cause) { if (!cause.collision || !window.confirm(`${cause.message} Replace it?`)) throw cause; next = installPack(packs, incoming, true); } for (const starter of incoming.starters) await onValidate(starter.document); write(next); setError(""); } catch (cause) { setError(cause.message); } }} /></label>{packs.map((pack) => <section className="checkpoint" key={pack.id}><h3>{pack.name}</h3><p>{Object.entries(pack.terms).map(([key, value]) => `${key}: ${value}`).join(" · ")}</p>{pack.starters.map((starter) => <button key={starter.name} onClick={() => onStart(structuredClone(starter.document), `${starter.name.replace(/[^a-z0-9_-]/gi, "-")}.${starter.document.diagram_type}.json`)}>Start {starter.name}</button>)}<button onClick={() => { document.documentElement.style.setProperty("--pack-accent", pack.theme.accent); localStorage.setItem("archify-pack-theme:v1", pack.theme.accent); }}>Apply editor accent</button><button onClick={() => { const current = JSON.parse(localStorage.getItem(templateKey) || "[]"), ids = new Set(pack.templates.map((entry) => entry.id)); localStorage.setItem(templateKey, JSON.stringify(checkTemplates([...current.filter((entry) => !ids.has(entry.id)), ...pack.templates]))); }}>Install reusable structures</button><button onClick={() => onDownload(pack, `${pack.id}.pack.json`)}>Export pack</button>{!builtInPacks.some((builtin) => builtin.id === pack.id) && <button onClick={() => write(packs.filter((entry) => entry.id !== pack.id))}>Remove pack</button>}</section>)}</div>;
}
