import React, { useState } from "react";
import { extensionKey, extensionGrantsKey, checkExtension, runExtensionCommand, runExtensionAdapter } from "./extensions.mjs";

export default function ExtensionsPanel({ document, onValidate, onApply, onDownload }) {
  const read = () => { try { const value = JSON.parse(localStorage.getItem(extensionKey) || "[]"); return Array.isArray(value) ? value.map(checkExtension) : []; } catch { return []; } };
  const [extensions, setExtensions] = useState(read), [grants, setGrants] = useState(() => { try { return JSON.parse(localStorage.getItem(extensionGrantsKey) || "{}"); } catch { return {}; } }), [error, setError] = useState("");
  const write = (next) => { localStorage.setItem(extensionKey, JSON.stringify(next)); setExtensions(next); };
  const saveGrants = (next) => { localStorage.setItem(extensionGrantsKey, JSON.stringify(next)); setGrants(next); };
  return <div className="properties"><h2>Local extensions</h2><p>Extensions are declarative JSON. No extension JavaScript is evaluated. Every requested permission must be granted before a command can run.</p>{error && <p role="alert">{error}</p>}<label className="field">Install extension manifest<input type="file" accept=".json,application/json" onChange={async (event) => { const file = event.target.files[0]; event.target.value = ""; if (!file) return; try { const manifest = checkExtension(JSON.parse(await file.text())); const next = [...extensions.filter((entry) => entry.id !== manifest.id), manifest]; write(next); setError(""); } catch (cause) { setError(cause.message); } }} /></label>{extensions.map((extension) => <section className="checkpoint" key={extension.id}><h3>{extension.name}</h3><p>{extension.id} · permissions: {extension.permissions.join(", ") || "none"}</p>{extension.permissions.map((permission) => <label className="check-row" key={permission}><input type="checkbox" checked={grants[extension.id]?.includes(permission) || false} onChange={(event) => saveGrants({ ...grants, [extension.id]: event.target.checked ? [...(grants[extension.id] || []), permission] : (grants[extension.id] || []).filter((entry) => entry !== permission) })} />Grant {permission}</label>)}{extension.commands.map((command) => <button key={command.id} onClick={async () => { try { const next = runExtensionCommand(extension, command.id, document, grants[extension.id] || []); await onValidate(next); onApply(next); setError(""); } catch (cause) { setError(cause.message); } }}>{command.label}</button>)}{(extension.adapters || []).map((adapter) => <button key={adapter.id} disabled={document.diagram_type !== adapter.from} onClick={async () => { try { const next = runExtensionAdapter(extension, adapter.id, document, grants[extension.id] || []); await onValidate(next); onApply(next); setError(""); } catch (cause) { setError(cause.message); } }}>{adapter.label}</button>)}<button onClick={() => onDownload(extension, `${extension.id}.extension.json`)}>Export</button><button onClick={() => { write(extensions.filter((entry) => entry.id !== extension.id)); const next = { ...grants }; delete next[extension.id]; saveGrants(next); }}>Remove</button></section>)}{!extensions.length && <p>No extensions installed.</p>}</div>;
}
