import React, { useState } from "react";
import { addPort, removePort, migrateArchitectureToV2 } from "./architecture-migration.mjs";

export default function PortsPanel({ document, selection, edgeIndex, onValidate, onApply }) {
  const [id, setId] = useState("port-1"), [side, setSide] = useState("right"), [offset, setOffset] = useState(0.5), [error, setError] = useState("");
  if (document.diagram_type !== "architecture") return <div className="properties"><h2>Persisted ports</h2><p>Ports are available for architecture diagrams.</p></div>;
  const component = selection.length === 1 ? document.components.find((item) => item.id === selection[0]) : null, edge = Number.isInteger(edgeIndex) ? document.connections?.[edgeIndex] : null;
  const apply = async (next) => { try { await onValidate(next); onApply(next); setError(""); } catch (cause) { setError(cause.message); } };
  const portsFor = (componentId) => document.components.find((item) => item.id === componentId)?.ports || [];
  return <div className="properties"><h2>Persisted ports</h2><p>Architecture v2 stores named endpoint positions. Migration is explicit and adds no inferred ports.</p>{error && <p role="alert">{error}</p>}{document.schema_version === 1 && <button onClick={() => apply(migrateArchitectureToV2(document).document)}>Migrate architecture v1 → v2</button>}{document.schema_version === 2 && <>{component ? <><h3>{component.label}</h3><form onSubmit={(event) => { event.preventDefault(); apply(addPort(document, component.id, { id, side, offset })); }}><label className="field">Port ID<input value={id} required onChange={(event) => setId(event.target.value)} /></label><label className="field">Side<select value={side} onChange={(event) => setSide(event.target.value)}>{["top", "right", "bottom", "left"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="field">Offset<input type="number" min="0" max="1" step="0.05" value={offset} onChange={(event) => setOffset(Number(event.target.value))} /></label><button>Add port</button></form>{(component.ports || []).map((port) => <section className="checkpoint" key={port.id}><strong>{port.id}</strong> · {port.side} {port.offset}<button onClick={() => apply(removePort(document, port.id))}>Remove</button></section>)}</> : <p>Select one component to add or remove ports.</p>}{edge && <><h3>Selected connection</h3>{[["fromPort", edge.from], ["toPort", edge.to]].map(([field, componentId]) => <label className="field" key={field}>{field}<select value={edge[field] || ""} onChange={(event) => { const next = structuredClone(document); if (event.target.value) next.connections[edgeIndex][field] = event.target.value; else delete next.connections[edgeIndex][field]; apply(next); }}><option value="">Automatic endpoint</option>{portsFor(componentId).map((port) => <option key={port.id} value={port.id}>{port.label || port.id}</option>)}</select></label>)}</>}</>}</div>;
}
