import {test,expect} from '@playwright/test';
test('segment handles move both waypoints with keyboard and cancel a pointer drag',async({page})=>{
 await page.goto('/');await page.locator('.connection-list summary').click();await page.getByRole('button',{name:'users → cdn',exact:true}).click();const input=page.getByLabel('Waypoints · [[x, y], …]');await input.fill('[[180,240],[230,240]]');await input.press('Tab');const handle=page.getByRole('button',{name:'Move horizontal segment 1'});await handle.focus();await page.keyboard.press('Shift+ArrowDown');await expect(input).toHaveValue('[[180,250],[230,250]]');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(input).toHaveValue('[[180,240],[230,240]]');const box=await handle.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2,box.y+50,{steps:6});await page.keyboard.press('Escape');await page.mouse.up();await expect(input).toHaveValue('[[180,240],[230,240]]');const again=await handle.boundingBox();await page.mouse.move(again.x+again.width/2,again.y+again.height/2);await page.mouse.down();await page.mouse.move(again.x+again.width/2,again.y+45,{steps:5});await page.mouse.up();const moved=JSON.parse(await input.inputValue());expect(moved[0][0]).toBe(180);expect(moved[1][0]).toBe(230);expect(moved[0][1]).toBe(moved[1][1]);expect(moved[0][1]).not.toBe(240);await page.screenshot({path:'test-results/segment-edit.png'});await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(input).toHaveValue('[[180,240],[230,240]]');
});
test('directed arrangement exposes direction and spacing before preview',async({page})=>{
 await page.goto('/');await page.locator('.react-flow__node-component').first().click();await page.locator('.react-flow__node-component').nth(1).click({modifiers:['Shift']});await page.getByRole('button',{name:'Auto-arrange',exact:true}).click();await page.getByLabel('Layout method').selectOption('directed');await page.getByLabel('Layout direction').selectOption('down');await page.getByLabel('Layout spacing').fill('100');await page.getByRole('button',{name:'Preview arrangement'}).click();await expect(page.getByLabel('Arrangement preview')).toBeVisible();await page.screenshot({path:'test-results/directed-preview.png'});await page.getByRole('button',{name:'Apply arrangement'}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();
});

test('full canvas arrangement preview is cancellable and guards authoring',async({page})=>{
 await page.goto('/');const nodes=page.locator('.react-flow__node-component');await nodes.first().click();await nodes.nth(1).click({modifiers:['Shift']});
 const position=await nodes.first().getAttribute('style');await page.getByRole('button',{name:'Auto-arrange',exact:true}).click();await page.getByRole('button',{name:'Preview arrangement'}).click();
 await expect(page.getByLabel('Arrangement preview')).toBeVisible();await expect(nodes.first()).not.toHaveAttribute('style',position);await expect(page.getByRole('button',{name:'Add component',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Download JSON',exact:true})).toBeDisabled();
 await page.screenshot({path:'test-results/full-canvas-preview.png'});await page.keyboard.press('Escape');await expect(nodes.first()).toHaveAttribute('style',position);await expect(page.getByLabel('Arrangement preview')).toHaveCount(0);
});

