import {test,expect} from '@playwright/test';
test('interrupted drag and route preview cancel without committing geometry',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Users users',exact:true}).click();const x=await page.getByLabel('X',{exact:true}).inputValue(),box=await page.locator('[data-id="c:users"]').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+30,box.y+box.height/2+20,{steps:5});await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.mouse.up();await expect(page.getByLabel('X',{exact:true})).toHaveValue(x);await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();await page.locator('.connection-list summary').click();await page.getByRole('button',{name:'users → cdn',exact:true}).click();await page.getByRole('button',{name:'Preview straight route',exact:true}).click();await expect(page.getByRole('button',{name:'Download JSON',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Download JSON',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();
});

test('inline canvas labels apply with Enter and cancel with Escape',async({page})=>{
 await page.goto('/');const label=page.locator('[data-id="c:users"] strong');await label.dblclick();await page.getByLabel('Edit canvas label',{exact:true}).fill('Customers');await page.getByLabel('Edit canvas label',{exact:true}).press('Enter');await expect(label).toHaveText('Customers');await label.dblclick();await page.getByLabel('Edit canvas label',{exact:true}).fill('Cancelled');await page.getByLabel('Edit canvas label',{exact:true}).press('Escape');await expect(label).toHaveText('Customers');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(label).toHaveText('Users');
});

test('context actions duplicate with undo and open by keyboard',async({page})=>{
 await page.goto('/');const node=page.locator('[data-id="c:users"]');await node.click({button:'right'});await expect(page.getByRole('dialog',{name:'Component actions'})).toBeVisible();await page.getByRole('button',{name:'Duplicate selection',exact:true}).click();await expect(page.locator('.react-flow__node-component')).toHaveCount(11);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.react-flow__node-component')).toHaveCount(10);await node.focus();await page.keyboard.press('Shift+F10');await expect(page.getByRole('dialog',{name:'Component actions'})).toBeVisible();await page.keyboard.press('Escape');await expect(node).toBeFocused();
});

test('focus mode expands canvas and panel widths persist separately from JSON',async({page})=>{
 await page.goto('/');await page.getByText('Panel sizes',{exact:true}).click();await page.getByLabel('Outline width',{exact:true}).fill('300');await page.getByText('Panel sizes',{exact:true}).click();await expect(page.locator('.outline')).toHaveCSS('width','300px');await page.getByRole('button',{name:'Focus mode',exact:true}).click();await expect(page.locator('.inspector')).toBeHidden();await expect(page.locator('.outline')).toBeHidden();await page.screenshot({path:'test-results/focus-mode.png'});await page.getByRole('button',{name:'Exit focus mode',exact:true}).click();await page.reload();await expect(page.locator('.outline')).toHaveCSS('width','300px');await page.getByRole('button',{name:'Undo',exact:true}).isDisabled();
});

test('insertion preview splits a connection and undo restores it',async({page})=>{
 await page.goto('/');await page.locator('.connection-list summary').click();await page.getByRole('button',{name:'users → cdn',exact:true}).click();await page.getByText('Insert component',{exact:true}).click();await page.getByLabel('Inserted component label',{exact:true}).fill('Gateway');await page.getByRole('button',{name:'Preview insertion',exact:true}).click();await expect(page.getByText('Insertion preview · JSON unchanged',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Apply route',exact:true}).click();await expect(page.locator('.react-flow__node-component')).toHaveCount(11);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.react-flow__node-component')).toHaveCount(10);
});

test('overlap resolution uses cancellable arrangement preview',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Users users',exact:true}).click();await page.getByLabel('X',{exact:true}).fill('300');await page.getByLabel('X',{exact:true}).press('Tab');await page.getByRole('button',{name:'Auto-arrange',exact:true}).click();await page.getByLabel('Layout method').selectOption('resolve');await page.getByRole('button',{name:'Preview arrangement',exact:true}).click();await expect(page.getByLabel('Arrangement preview')).toBeVisible();await page.getByRole('button',{name:'Cancel arrangement',exact:true}).click();await page.getByRole('button',{name:'Properties',exact:true}).click();await expect(page.getByLabel('X',{exact:true})).toHaveValue('300');
});

test('layout presets restore layout options without a document edit',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Auto-arrange',exact:true}).click();await page.getByLabel('Layout method').selectOption('anchored');await page.getByLabel('Layout spacing').fill('90');await page.getByText('Layout presets',{exact:true}).click();await page.getByLabel('Preset name',{exact:true}).fill('My spacing');await page.getByRole('button',{name:'Save layout preset',exact:true}).click();await page.getByLabel('Layout spacing').fill('30');await page.getByRole('button',{name:'Use My spacing',exact:true}).click();await expect(page.getByLabel('Layout spacing')).toHaveValue('90');await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();await page.reload();await page.getByText('Layout presets',{exact:true}).click();await page.getByRole('button',{name:'Use My spacing',exact:true}).click();await expect(page.getByLabel('Layout method')).toHaveValue('anchored');
});

test('recovery restores undo and redo alongside the applied draft',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Users users',exact:true}).click();await page.getByLabel('X',{exact:true}).fill('60');await page.getByLabel('X',{exact:true}).press('Tab');await page.getByLabel('X',{exact:true}).fill('80');await page.getByLabel('X',{exact:true}).press('Tab');await page.getByRole('button',{name:'Undo',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Restore draft',exact:true}).click();await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Redo',exact:true}).click();await page.getByRole('button',{name:'Users users',exact:true}).click();await expect(page.getByLabel('X',{exact:true})).toHaveValue('80');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByLabel('X',{exact:true})).toHaveValue('60');
});
